version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=groeigids-api-client-bundle"
    volumes:
      - .:/var/www/html:cached
      - ./coverage:/opt/phpstorm-coverage
    command: tail -f /dev/null